#!/bin/bash

# App token
TOKEN="azc5............."

# User key
USER="uek4................"

curl -s \
 -F "user=$USER" \
 -F "token=$TOKEN" \
 -F 'title="Pushover Notification"' \
 -F "message=$1" \
 https://api.pushover.net/1/messages.json
